name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
    always: true

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    default_python: '3.8'
    submodules: false
    coverage: codecov
    toxdeps: tox-pypi-filter
    libraries:
      apt:
        - graphviz

    envs:
      - macos: py38
        name: py38_test

      - windows: py37
        name: py37_test

      - linux: py38-online
        name: py38_test_online

      - linux: py38-sunpy
        name: py38_test_sunpy_online

      - linux: codestyle
        name: python_codestyle
        pytest: false

      - linux: build_docs
        posargs: " "
        pytest: false

# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'PyPI'
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst --pyargs drms'
      submodules: false
      targets:
        - wheels_universal
        - sdist
      dependsOn:
        - py37_test
        - py38_test
        - py38_test_online
