# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.6.4.dev18+g4fe102f.d20230327'
__version_tuple__ = version_tuple = (0, 6, 4, 'dev18', 'g4fe102f.d20230327')
