# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.6.5.dev4+g75555be.d20230609"
__version_tuple__ = version_tuple = (0, 6, 5, "dev4", "g75555be.d20230609")
